apiVersion: v1
kind: ConfigMap
metadata:
  name: pragent-config
  namespace: pr-agent
data:
  LANGFUSE_HOST: https://cloud.langfuse.com
  # OPENSEARCH_HOST: "https://opensearch-cluster-master.default.svc.cluster.local:9200"
  OPENSEARCH_HOST: https://search-initiativellm-oftimxbb2qk7mt7pzlvfzmz3ga.ap-southeast-1.es.amazonaws.com
