apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-sc
  resources:
    requests:
      storage: 5Gi