apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: password^2025
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: n8nuser
  POSTGRES_NON_ROOT_PASSWORD: password^2025