---
serviceAccount:
  name: argocd-image-updater

authScripts:
  enabled: true
  scripts: 
    auth.sh: | 
      #!/bin/sh
      aws ecr --region ap-southeast-1 get-authorization-token --output text --query 'authorizationData[0].authorizationToken' | base64 -d

config:
  registries:
    - name: ECR
      api_url: https://535002848241.dkr.ecr.ap-southeast-1.amazonaws.com
      prefix: 535002848241.dkr.ecr.ap-southeast-1.amazonaws.com
      ping: yes
      insecure: no
      credentials: ext:/scripts/auth.sh
      credsexpire: 10h
